apiVersion: v1
kind: Service
metadata:
  name: whereami
spec:
  type: ClusterIP
  selector:
    app: whereami
  ports:
    - name: tomcat
      port: 8080
      targetPort: tomcat

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whereami
  labels:
    app: whereami
    version: v1
spec:
  selector:
    matchLabels:
      app: whereami
      version: v1
  replicas: 1
  template:
    metadata:
      name: whereami
      labels:
        app: whereami
        version: v1
    spec:
      containers:
        - name: whereami
          image: kubepia/whereami:latest
          imagePullPolicy: Always
          ports:
            - name: tomcat
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/health
              port: tomcat
            initialDelaySeconds: 5
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /api/health
              port: tomcat
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              memory: 2048Mi
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
